import type { AiMetadataPromptScope } from '@smart-dms/shared-dto';

export interface DefaultAiMetadataPrompt {
  readonly key: AiMetadataPromptScope;
  readonly label: string;
  readonly description: string;
  readonly promptText: string;
  readonly displayOrder: number;
}

export const DEFAULT_AI_METADATA_PROMPTS: readonly DefaultAiMetadataPrompt[] = [
  {
    key: 'TITLE',
    label: 'Title',
    description: 'Concise document title for lists and search.',
    displayOrder: 10,
    promptText:
      'Extract title: concise and descriptive, maximum 12 words, optimized for scanning large document lists. Prefer concrete document kind plus the most identifying party, organization, reference, period, or subject grounded in the document. Avoid generic role descriptions and titles that only restate the broad document category.',
  },
  {
    key: 'DOCUMENT_TYPE',
    label: 'Document type',
    description: 'Classification into one configured active document type.',
    displayOrder: 20,
    promptText:
      'Extract documentTypeKey. Choose exactly one key from Available active document types. Return the key value only, never the display name and never free text. A value outside the listed keys is invalid. If no category fits confidently and "other" exists, choose "other"; otherwise choose the closest available category.',
  },
  {
    key: 'SUMMARY',
    label: 'Summary',
    description: 'High-level document summary.',
    displayOrder: 40,
    promptText:
      "Extract summary: one coherent paragraph, maximum 180 words, that provides a high-level overview of the document content. Explain what the document is about, who or what it concerns, and the central purpose, request, decision, obligation, or information when evident. Do not list every extracted detail, line item, reference number, date, or amount; include only details that are essential to understand the document. Write in the document's primary language and avoid repeating the title verbatim.",
  },
  {
    key: 'TAGS',
    label: 'Tags',
    description: 'Reusable search and retrieval tags.',
    displayOrder: 50,
    promptText:
      'Extract tags: 5 to 15 lowercase search tags, no duplicates, optimized for full-text and AI retrieval. Use reusable topic, domain, process, intent, obligation, category, and synonym terms that describe the document content and help find similar documents. Do not include sender or recipient names, personal names, company names, addresses, contact data, IBANs, reference numbers, invoice numbers, customer numbers, or other document-specific identifiers. Prefer general searchable terms over one-off entities.',
  },
  {
    key: 'PARTIES',
    label: 'Parties',
    description: 'Sender and recipient metadata.',
    displayOrder: 60,
    promptText: [
      'Extract sender and recipient.',
      '',
      'sender:',
      '- The person, organization, authority, court, practice, vendor, or entity that issued or created the document.',
      '- Evidence priority for sender: letterhead/header organization, explicit issuer/vendor/provider/authority field, signature block, then footer organization only when it clearly identifies the issuer.',
      '- Use a concise concrete name or label.',
      '- Do not use payment recipient, account beneficiary, postal addressee, customer, legal counterparty mentioned only in the body, or vague labels such as unknown sender.',
      '- Use null if no concrete issuer is grounded in the OCR text.',
      '',
      'recipient:',
      '- The primary addressee: the person, organization, or entity that the sender is addressing in this document.',
      '- Determine sender first, then choose a distinct receiving-side party only when the OCR text grounds that party explicitly.',
      '- Evidence priority for recipient: postal addressee/address block near the top, explicit recipient/customer/patient/insured/bill-to section, direct salutation such as Dear, then other clearly labeled addressee fields.',
      '- Use the concrete person or organization named in that evidence, not the surrounding role label.',
      '- For invoices, offers, statements, and similar business documents, use the billed customer or offer recipient only if a customer/bill-to/recipient/addressee section explicitly names that party.',
      '- Do not use a payment recipient, payee, account beneficiary, bank account holder, invoice issuer, offer issuer, contact organization, footer organization, signature block, cc recipient, legal counterparty mentioned only in the body, or return-address sender as the document recipient.',
      '- If the document lists several parties, choose the one the document is directed to, not every participant mentioned in a case, contract, delivery, or payment flow.',
      '- Sender and recipient should be identical only when the document explicitly addresses itself to the issuer; otherwise use null if no distinct document addressee is grounded.',
      '- Use a concise concrete name or label.',
      '- Use null for generic roles, vague audiences, unknown recipient labels, or ungrounded guesses.',
      '- Do not append translations or bilingual role labels.',
    ].join('\n'),
  },
  {
    key: 'DOCUMENT_DATE',
    label: 'Document date',
    description: 'Issue or creation date of the document.',
    displayOrder: 70,
    promptText: [
      'Extract `documentDate` from the full OCR text.',
      '',
      '`documentDate` is the issue, creation, invoice, offer, decision, filing, notice, or letter date of the current document only.',
      '',
      'Return exactly one ISO 8601 datetime with timezone, or `null` if no reliable document date exists.',
      '',
      'Use only explicit date text that is clearly labeled or positioned as the current document date. Strong clues are labels whose meaning is document date, issue date, creation date, invoice date, offer date, decision date, filing date, notice date, letter date, or equivalent concepts in any document language.',
      '',
      'Extract from headers, letterheads, title blocks, invoice/offer metadata, official form metadata, authority/court headers, correspondence metadata, or DMS metadata only when the date refers to the current document.',
      '',
      'Do not use payment due dates, appointment dates, deadlines, response periods, service periods, delivery periods, booking dates, value dates, birth dates, report/table dates, print/generated timestamps, scan/OCR timestamps, receipt dates, processing dates, or background dates.',
      '',
      'Do not use body-text dates unless they explicitly describe the issue, creation, invoice, offer, decision, filing, notice, or letter date of the current document. Ignore dates belonging to previous letters, prior invoices, earlier decisions, reminders, referenced records, or incoming documents unless clearly marked as the current document date.',
      '',
      'If multiple candidates exist, prefer an explicitly labeled current-document date over header/title-block metadata, and prefer those over footer or technical metadata. Never use technical timestamps when a better issue-date candidate exists.',
      '',
      'Date-only values must become midnight UTC: `YYYY-MM-DDT00:00:00.000Z`. The result must start with a four-digit year, use hyphen-separated month and day, include `T` time, and end with `Z` or a numeric timezone offset. Never combine localized source date formats with an ISO time component. If the date order is ambiguous and cannot be resolved reliably, return `null`.',
      '',
      'Return `documentDate: null` when no reliable current-document date exists.',
    ].join('\n'),
  },
  {
    key: 'PAYMENTS',
    label: 'Payments',
    description: 'Payment instructions and requested amounts.',
    displayOrder: 80,
    promptText: [
      'Extract `payments` from the full OCR text only when the document clearly requests, demands, reminds, notifies, invoices, or instructs the recipient to pay money.',
      '',
      'A monetary amount alone is not a payment. Extract only amounts payable by the recipient. Ignore salaries, wages, payouts, refunds, credits, contract values, prices, budgets, insurance sums, damages, deposits, discounts, taxes, fees, line items, examples, tables, or financial background values unless the text explicitly requires payment of that amount.',
      '',
      'Return one item per independent payment obligation. For invoices with multiple line items but one payable total, extract only the total. For separate obligations with different amounts, recipients, purposes, or due dates, extract separate items.',
      '',
      'Include only fields clearly linked to the same payment obligation:',
      '- `amount`: payable amount',
      '- `currency`: currency',
      '- `recipient`: payee/account beneficiary, not necessarily the document recipient',
      "- `iban`: payee's IBAN/account",
      '- `purpose`: required payment reference or stated purpose',
      '- `dueDate`: date by which payment must be made, credited, completed, or received, as `YYYY-MM-DD`',
      '- `dueDateSourceText`: shortest triggering text for the due date',
      '',
      'Do not use invoice date, document date, service date, delivery date, booking date, value date, salary date, table date, or reminder date as `dueDate` unless explicitly stated as the payment deadline.',
      '',
      'Do not guess or merge data from isolated amounts, unrelated bank details, tables, examples, contract clauses, or background information. Detect payment semantics in any document language; labels are clues, not requirements.',
      '',
      'Return `payments: []` when money is mentioned but no payment is requested, demanded, reminded, notified, or instructed.',
    ].join('\n'),
  },
  {
    key: 'REFERENCES',
    label: 'References',
    description: 'Document and business context identifiers.',
    displayOrder: 90,
    promptText: [
      'Extract `references` from the full OCR text.',
      '',
      'Return only explicit identifiers that identify the document or a directly relevant business, legal, administrative, or transactional record, such as quote, invoice, customer, order, contract, file, case, claim, policy, account, transaction, receipt, booking, mandate, membership, process, ticket, or reference numbers.',
      '',
      'A number/code is a reference only when its context clearly labels or uses it as an identifier. Extract from headers, subject lines, metadata blocks, footers, correspondence metadata, or DMS metadata only when the identifier belongs to the document or a directly relevant record.',
      '',
      'For each item:',
      '- `referenceType`: use the concise document label in the same language, e.g. `Invoice number`, `Customer number`, `File number`, `Your reference`, `Order ID`. If no label exists but the identifier is clearly a reference, use a short generic type in the primary document language.',
      '- `value`: preserve exactly; trim surrounding whitespace only. Keep meaningful letters, casing, separators, punctuation, and leading zeros.',
      '',
      'Return one item per independent reference. Deduplicate repeated references. If the same value has multiple labels, prefer the most specific label.',
      '',
      'Do not extract dates, amounts, currencies, phone/fax numbers, email addresses, URLs, tax/VAT IDs, IBANs, BICs, postal codes, addresses, page numbers, table row numbers, quantities, prices, version numbers, product/article codes, random OCR fragments, or isolated numbers without a clear reference function.',
      '',
      'Do not treat invoice dates, document dates, delivery dates, service periods, due dates, birth dates, or report dates as references. Date-like values are references only when explicitly labeled as identifiers.',
      '',
      'Do not guess labels or merge unrelated fragments. Detect semantics in any document language.',
      '',
      'Return `references: []` when no reliable references exist.',
    ].join('\n'),
  },
  {
    key: 'ATTRIBUTES',
    label: 'Additional fields',
    description: 'Configured custom AI metadata fields.',
    displayOrder: 100,
    promptText:
      'Extract attributes: only use configured field definition keys and match valueType to the configured definition. Use [] when no configured attribute is present.',
  },
  {
    key: 'CALENDAR_EVENTS',
    label: 'Calendar events',
    description: 'Appointments, due dates, and deadlines.',
    displayOrder: 110,
    promptText: [
      'Extract `calendarEvents` from the full OCR text.',
      '',
      'Return every independent actionable date relationship as a separate item. Do not stop after the first date; one document may contain multiple appointments, deadlines, payment dates, or response windows.',
      '',
      'A date is relevant only when its context schedules, limits, enables, or triggers an action. Include appointments, due dates, response/payment/procedural periods, objection/cancellation/submission deadlines, obligations, and recurring actionable dates.',
      '',
      'Before extracting, classify each date-like candidate as:',
      '1. ACTIONABLE_EVENT -> extract.',
      '2. NON_EVENT_METADATA -> ignore.',
      '',
      'Extract dates linked to actions such as paying, responding, submitting, objecting, cancelling, sending, providing, attending, appearing, or completing something.',
      '',
      'Ignore dates or date-like values used only for completed facts, background/accounting info, wage/salary payout dates, value dates, service/delivery periods, birth dates, print/report/table dates, document metadata, versions, releases, builds, models, articles, identifiers, reference codes, tariffs, product/package/module/edition names, or labels.',
      '',
      'Do not interpret values like `1.2`, `01/24`, `2024-01`, `v2.4`, `Tarif 12.24`, or `Release 10/23` as dates when their context indicates a version, code, period, product, tariff, model, identifier, or label. A two-part numeric value without an explicit year is not enough. Never infer missing years.',
      '',
      'For windows/periods, extract the actionable boundary: usually the end date as `DEADLINE`; extract the start date only if it triggers, enables, or schedules an action.',
      '',
      'Classify:',
      '- `APPOINTMENT`: scheduled meeting, hearing, visit, appearance, appointment.',
      '- `DUE_DATE`: payment must be made/completed/received by this date.',
      '- `DEADLINE`: non-payment action limit, e.g. response, objection, cancellation, submission, sending, providing, completion.',
      '',
      'If a payment date is already represented as `payments.dueDate`, do not create a second independent calendar item. You may include one matching `DUE_DATE` calendar event only when it preserves the document-language action title or source wording for that same payment date.',
      '',
      'Absolute dates: use `date` as `YYYY-MM-DD`; use `time` as `HH:mm` only when explicit.',
      '',
      'Relative dates: when an actionable event is defined by an explicit numeric duration relative to the document issue date, return `relativeDate` and do not calculate the final date:',
      '- `amount`: numeric duration, including clear number words',
      '- `unit`: `DAYS` or `WEEKS`',
      '- `anchor`: `DOCUMENT_DATE`',
      '',
      'Return an item only if `date` or `relativeDate` can be populated. Do not extract `documentDate` unless it is explicitly also an appointment, deadline, or due date.',
      '',
      'Detect semantics across any document language. Labels are clues, not requirements. Include the shortest useful triggering fragment in `sourceText`.',
      '',
      'If no actionable event exists, return `calendarEvents: []`.',
    ].join('\n'),
  },
];

export function defaultPromptByScope(
  key: AiMetadataPromptScope,
): DefaultAiMetadataPrompt {
  const prompt = DEFAULT_AI_METADATA_PROMPTS.find((entry) => entry.key === key);
  if (!prompt) {
    throw new Error(`Unknown AI metadata prompt scope: ${key}`);
  }

  return prompt;
}
