import type { EvidenceTriggerSet } from './types';

export const deuEvidenceTriggers: EvidenceTriggerSet = {
  payment: [
    'abbuchung',
    'abschlag',
    'betrag',
    'bruttobetrag',
    'einzug',
    'faellig',
    'fällig',
    'gesamtbetrag',
    'gutschrift',
    'iban',
    'mahnung',
    'netto',
    'offener betrag',
    'rabatt',
    'rechnung',
    'rechnungsbetrag',
    'rate',
    'ratenzahlung',
    'saldo',
    'sepa',
    'skonto',
    'ueberweisung',
    'ueberweisen',
    'überweisung',
    'überweisen',
    'verwendungszweck',
    'vorkasse',
    'zahlbar',
    'zahlen',
    'zahlung',
    'zahlungseingang',
    'zahlungsfrist',
    'zu zahlen',
  ],
  calendar: [
    'antworten sie bis',
    'begehung',
    'besprechung',
    'bis spaetestens',
    'bis spätestens',
    'bis zum',
    'einladung',
    'faellig',
    'fällig',
    'frist',
    'fristablauf',
    'innerhalb',
    'innerhalb von',
    'kuendigung',
    'kündigung',
    'letzter termin',
    'mahnung',
    'nachfrist',
    'rueckmeldung',
    'rückmeldung',
    'spaetestens',
    'spätestens',
    'termin',
    'terminbestaetigung',
    'terminbestätigung',
    'veranstaltung',
    'widerspruch',
    'zahlbar',
    'zahlungsfrist',
  ],
  party: [
    'absender',
    'auftraggeber',
    'auftragnehmer',
    'aussteller',
    'empfaenger',
    'empfänger',
    'frau',
    'herr',
    'herrn',
    'kunde',
    'lieferant',
    'name',
    'rechnung an',
    'rechnungsempfaenger',
    'rechnungsempfänger',
    'sehr geehrte',
    'sehr geehrter',
    'von',
  ],
  attribute: [
    'abteilung',
    'aktenzeichen',
    'auftragsnummer',
    'bestellnummer',
    'filiale',
    'kennzeichen',
    'konto',
    'kostenstelle',
    'mandant',
    'objekt',
    'personalnummer',
    'projekt',
    'referat',
    'sachbearbeiter',
    'standort',
    'vertragsnummer',
  ],
  referenceLabels: [
    'angebot',
    'angebots-nr.',
    'angebotsnummer',
    'auftrag',
    'auftrags-nr.',
    'auftragsnummer',
    'aktenzeichen',
    'beleg',
    'beleg-nr.',
    'belegnummer',
    'bestell-nr.',
    'bestellnummer',
    'bv',
    'fall',
    'kunden-nr.',
    'kundennummer',
    'mandatsreferenz',
    'police',
    'referenz',
    'rechnung',
    'rechnungs-nr.',
    'rechnungsnummer',
    'schaden',
    'vorgang',
    'vertrag',
    'vertrags-nr.',
    'vertragsnummer',
    'zeichen',
  ],
  gluedNextLabels: [
    'angebot',
    'auftrag',
    'datum',
    'frau',
    'herr',
    'herrn',
    'kunde',
    'kunden-nr.',
    'kundennr.',
    'liefer-/leistungsdatum',
    'lieferdatum',
    'name',
    'rechnung',
    'sachbearbeiter',
    'sachbearbeiter/-in',
    'seite',
  ],
  trailingOcrLabels: [
    'angebot',
    'auftrag',
    'datum',
    'frau',
    'herr',
    'herrn',
    'kunde',
    'kunden',
    'kundennr',
    'liefer',
    'leistungsdatum',
    'name',
    'rechnung',
    'sachbearbeiter',
    'seite',
  ],
};
