import type { EvidenceTriggerSet } from './types';

export const engEvidenceTriggers: EvidenceTriggerSet = {
  payment: [
    'amount due',
    'balance due',
    'bank account',
    'billing',
    'charge',
    'credit note',
    'deposit',
    'due',
    'iban',
    'invoice',
    'net amount',
    'paid',
    'pay',
    'payable',
    'payment',
    'payment due',
    'payment terms',
    'remit',
    'remittance',
    'subtotal',
    'total',
    'transfer',
    'wire transfer',
  ],
  calendar: [
    'appointment',
    'cancellation',
    'deadline',
    'due',
    'due date',
    'event',
    'hearing',
    'meeting',
    'no later than',
    'objection',
    'payable',
    'reply by',
    'respond by',
    'response deadline',
    'scheduled',
    'submission deadline',
    'termination',
    'within',
  ],
  party: [
    'applicant',
    'bill to',
    'buyer',
    'customer',
    'dear',
    'from',
    'issuer',
    'recipient',
    'sender',
    'ship to',
    'supplier',
    'vendor',
  ],
  attribute: [
    'account',
    'case number',
    'cost center',
    'department',
    'license plate',
    'location',
    'object',
    'order number',
    'policy number',
    'project',
    'property',
    'reference',
    'site',
  ],
  referenceLabels: [
    'account',
    'account no.',
    'booking',
    'case',
    'case no.',
    'claim',
    'claim no.',
    'contract',
    'contract no.',
    'customer',
    'customer no.',
    'file',
    'file no.',
    'inv.',
    'invoice',
    'invoice no.',
    'invoice number',
    'order',
    'order no.',
    'policy',
    'policy no.',
    'quote',
    'quote no.',
    'receipt',
    'receipt no.',
    'reference',
    'reference no.',
    'transaction',
    'transaction no.',
  ],
  gluedNextLabels: [
    'agent',
    'bill to',
    'customer',
    'customer no.',
    'date',
    'delivery date',
    'invoice',
    'name',
    'order',
    'page',
    'quote',
    'ship to',
  ],
  trailingOcrLabels: [
    'agent',
    'billto',
    'customer',
    'date',
    'delivery',
    'invoice',
    'name',
    'order',
    'page',
    'quote',
    'shipto',
  ],
};
