import type { EvidenceTriggerSet } from './types';

export const fraEvidenceTriggers: EvidenceTriggerSet = {
  payment: [
    'acompte',
    'a payer',
    'à payer',
    'avis de paiement',
    'banque',
    'echeance',
    'échéance',
    'facture',
    'iban',
    'montant',
    'montant du',
    'montant dû',
    'paiement',
    'payer',
    'prelevement',
    'prélèvement',
    'reglement',
    'règlement',
    'reste a payer',
    'reste à payer',
    'solde',
    'total',
    'virement',
  ],
  calendar: [
    'audience',
    'avant le',
    'convocation',
    'date limite',
    'delai',
    'délai',
    'echeance',
    'échéance',
    'entretien',
    'evenement',
    'événement',
    'jusqu au',
    'jusqu’au',
    'limite',
    'paiement',
    'rendez-vous',
    'repondre avant',
    'répondre avant',
    'resiliation',
    'résiliation',
    'sous',
  ],
  party: [
    'acheteur',
    'client',
    'destinataire',
    'emetteur',
    'émetteur',
    'expediteur',
    'expéditeur',
    'facture a',
    'facture à',
    'fournisseur',
    'madame',
    'monsieur',
  ],
  attribute: [
    'agence',
    'centre de cout',
    'centre de coût',
    'compte',
    'departement',
    'département',
    'dossier',
    'immatriculation',
    'objet',
    'projet',
    'service',
    'site',
  ],
  referenceLabels: [
    'commande',
    'commande n°',
    'contrat',
    'contrat n°',
    'devis',
    'devis n°',
    'dossier',
    'dossier n°',
    'facture',
    'facture n°',
    'numero de client',
    'numéro de client',
    'police',
    'police n°',
    'recu',
    'reçu',
    'reference',
    'référence',
    'reference n°',
    'référence n°',
    'sinistre',
    'transaction',
  ],
  gluedNextLabels: [
    'client',
    'commande',
    'date',
    'date de livraison',
    'destinataire',
    'devis',
    'facture',
    'madame',
    'monsieur',
    'nom',
    'page',
  ],
  trailingOcrLabels: [
    'client',
    'commande',
    'date',
    'devis',
    'facture',
    'livraison',
    'madame',
    'monsieur',
    'nom',
    'page',
  ],
};
