import type { EvidenceTriggerSet } from './types';

export const porEvidenceTriggers: EvidenceTriggerSet = {
  payment: [
    'adiantamento',
    'a pagar',
    'banco',
    'boleto',
    'cobrança',
    'conta bancaria',
    'conta bancária',
    'debito',
    'débito',
    'fatura',
    'forma de pagamento',
    'iban',
    'montante',
    'pagamento',
    'pagar',
    'saldo',
    'total',
    'transferencia',
    'transferência',
    'valor',
    'valor devido',
    'vencimento',
  ],
  calendar: [
    'até',
    'audiencia',
    'audiência',
    'compromisso',
    'convocacao',
    'convocação',
    'data limite',
    'dentro de',
    'prazo',
    'reuniao',
    'reunião',
    'responder ate',
    'responder até',
    'vencimento',
    'visita',
  ],
  party: [
    'cliente',
    'destinatario',
    'destinatário',
    'emitente',
    'faturar a',
    'fornecedor',
    'para',
    'prezado',
    'prezada',
    'remetente',
    'senhor',
    'senhora',
  ],
  attribute: [
    'centro de custo',
    'conta',
    'departamento',
    'escritorio',
    'escritório',
    'local',
    'matricula',
    'matrícula',
    'objeto',
    'processo',
    'projeto',
  ],
  referenceLabels: [
    'apolice',
    'apólice',
    'caso',
    'cliente',
    'cliente n°',
    'contrato',
    'contrato n°',
    'cotacao',
    'cotação',
    'fatura',
    'fatura n°',
    'numero do cliente',
    'número do cliente',
    'pedido',
    'pedido n°',
    'processo',
    'recibo',
    'referencia',
    'referência',
    'referencia n°',
    'referência n°',
    'sinistro',
    'transacao',
    'transação',
  ],
  gluedNextLabels: [
    'cliente',
    'data',
    'data de entrega',
    'fatura',
    'nome',
    'pagina',
    'página',
    'pedido',
    'senhor',
    'senhora',
  ],
  trailingOcrLabels: [
    'cliente',
    'data',
    'entrega',
    'fatura',
    'nome',
    'pagina',
    'página',
    'pedido',
    'senhor',
    'senhora',
  ],
};
