import type { EvidenceTriggerSet } from './types';

export const spaEvidenceTriggers: EvidenceTriggerSet = {
  payment: [
    'abonar',
    'adeudo',
    'anticipo',
    'banco',
    'cargo',
    'cuenta bancaria',
    'factura',
    'forma de pago',
    'iban',
    'importe',
    'importe adeudado',
    'importe total',
    'pagar',
    'pagadero',
    'pago',
    'pendiente de pago',
    'saldo',
    'total',
    'transferencia',
    'vencimiento',
  ],
  calendar: [
    'audiencia',
    'cita',
    'convocatoria',
    'dentro de',
    'fecha limite',
    'fecha límite',
    'hasta el',
    'plazo',
    'reunion',
    'reunión',
    'responder antes',
    'vencimiento',
    'visita',
  ],
  party: [
    'cliente',
    'destinatario',
    'emisor',
    'estimado',
    'estimada',
    'facturar a',
    'para',
    'proveedor',
    'remitente',
    'senor',
    'señor',
    'senora',
    'señora',
  ],
  attribute: [
    'centro de coste',
    'contrato',
    'cuenta',
    'departamento',
    'expediente',
    'matricula',
    'matrícula',
    'objeto',
    'oficina',
    'proyecto',
    'sede',
  ],
  referenceLabels: [
    'caso',
    'cliente',
    'cliente n°',
    'contrato',
    'contrato n°',
    'expediente',
    'factura',
    'factura n°',
    'número de cliente',
    'oferta',
    'oferta n°',
    'pedido',
    'pedido n°',
    'poliza',
    'póliza',
    'recibo',
    'referencia',
    'referencia n°',
    'siniestro',
    'transaccion',
    'transacción',
  ],
  gluedNextLabels: [
    'cliente',
    'fecha',
    'fecha de entrega',
    'factura',
    'nombre',
    'oferta',
    'pagina',
    'página',
    'pedido',
    'senor',
    'señor',
    'senora',
    'señora',
  ],
  trailingOcrLabels: [
    'cliente',
    'entrega',
    'fecha',
    'factura',
    'nombre',
    'oferta',
    'pagina',
    'página',
    'pedido',
    'senor',
    'señor',
    'senora',
    'señora',
  ],
};
